version: '3.8'
services:
  db:
    image: postgres:15
    container_name: hardware-catalog-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin123}
      POSTGRES_DB: ${POSTGRES_DB:-hardware_catalog}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hardware-catalog-web
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      POSTGRES_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-admin123}@db:5432/${POSTGRES_DB:-hardware_catalog}
      JWT_SECRET: ${JWT_SECRET:-your-very-secret-key}

volumes:
  postgres_data: 